#!/bin/bash -e
# Copyright (C) 2010-2016 GRNET S.A.
#
# Author:
#     Apollon Oikonomopoulos <apoikos@gmail.com>
#
# License:
#
#     This package is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.
#
#     This package is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this package; if not, write to the Free Software
#     Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#
# On Debian systems, the complete text of the GNU General
# Public License can be found in `/usr/share/common-licenses/GPL'.

# Note: dash does not support redirecting file descriptors above 9,
# but ganeti typically passes 11. Hence this must be run under bash.
# https://bugs.launchpad.net/ubuntu/+source/dash/+bug/249620

if test -n "$EXP_SIZE_FD"; then
  blockdev --getsize64 "$EXPORT_DEVICE" >&"$EXP_SIZE_FD"
fi

dd if="$EXPORT_DEVICE" bs=1048576
